### PR TITLE
Fix startup files order when placing tabs next to the current one

### LINKED ISSUE #3609: Restoring the session does not restore the current file or files order when tabs_order_beside is enabled
Restoring the session (from my upgraded ~/.config, which has seen all versions since the dawn of time^W^W^W^W I started using Geany) restores the files, but not:

* the order
* the current file

It kinda looks like the first element is right, but the reset is sort of loaded in reverse… Might have something to do with the option on where new tabs are opened?

### PR DESCRIPTION
**Pull request by b4n**
When the `tab_order_beside` option is enabled, tabs are opened on either side of the active tab, depending on `tab_order_ltr`, rather than at either end.

However, when loading startup files we don't switch to the last opened document right away, but postpone this to the very end.  This affects the order tabs are loaded, as the active one is always the first one at this stage.

Rather than over-complicating the loading order to compensate the various options' effect, temporarily revert to an set of options that is easy to handle, and restore it after loading is finished.  This also simplifies the existing logic as a basic forward iteration is now enough.

Fixes #3609.

### CODE REVIEW

**Comment by elextr** [comment]
LGBI

**Comment by techee** [comment]
> @eht16 @techee @elextr I added that to %2.0, but if it's not new since 1.38 and you don't feel it's simple enough, we can postpone. It's actually not a problem with the default settings, so it's less bad -- although any sane person would have enabled the problematic option 😁

Looks good to me based on the code itself and I think it could go to 2.0. I just haven't tested it yet (which I'm going to do now).

**Comment by techee** [comment]
> Looks good to me based on the code itself and I think it could go to 2.0. I just haven't tested it yet (which I'm going to do now).

I just tested it and, yes, it is fixed, and, yes, the re-arrangement is really annoying without this patch so I think it should go to 2.0. (Somehow, I didn't have the option to place new tabs behind the current one enabled so I didn't notice the problem.)

One unrelated glitch I noticed is that when you close Geany with some files opened, and then open it from the command-line with some file as an argument, this file is always opened in the second tab - I would expect it to open behind the tab which was last active when Geany closed. I expect that when the command-line file gets opened, the "current" file is still the first one so it appears behind it. But not really a big problem and maybe even not worth fixing as users hopefully forget which tab was active when they closed Geany :-).

**Review by techee — APPROVED** [review]

**Comment by kugel-** [comment]
Actually if it's like this in 1.38 already (and possibly earlier) I see no compelling reason to rush this into 2.0, considering that tomorrow is release.

It's not even clear to me if this is even a bug (as on "not working as intended"). I surely never used that pref.

File: src/keyfile.c [hunk 1]
```diff
@@ -1356,14 +1356,17 @@ static gboolean open_session_file(gchar **tmp, guint len)
...
+	const gboolean save_tab_order_beside = file_prefs.tab_order_beside;
+	const gboolean save_tab_order_ltr = file_prefs.tab_order_ltr;
 
 	/* necessary to set it to TRUE for project session support */
 	main_status.opening_session_files++;
 
-	i = file_prefs.tab_order_ltr ? 0 : (session_files->len - 1);
-	while (TRUE)
+	file_prefs.tab_order_beside = FALSE;
+	file_prefs.tab_order_ltr = TRUE;
```
Comment (kugel-) [inline src/keyfile.c:1367]: Why do you override the pref temporarily? Is there some nested function call that looks at the pref?

**Comment by eht16** [comment]
> although any sane person would have enabled the problematic option 😁

@b4n Hah, it seems you have proven me as crazy again, my config says `tab_order_beside=false` :)

File: src/keyfile.c (hunk 1 above)
Comment (b4n) [reply src/keyfile.c:1367]: Yes, `notebook_new_tab()`.  Call chain is `open_session_file() → document_open_file_full() → document_create() → notebook_new_tab()`.

**Comment by eht16** [comment]
> It's not even clear to me if this is even a bug (as in "not working as intended"). I surely never used that pref.

I hardly can imagine this could be intended behaviour. After start, the previous code opened the tabs in some random (maybe not really random but in some for the user undeterministic order) and after a second start the previous order was restored, on the third start the pseudo random order of the first start is used and so on.
At least me would be very confused by this. I don't mind much if this is a new issue or already present in 1.38, since we have a fix already and it is rather trivial, I'm still for merging.

**Comment by b4n** [comment]
@kugel- 
> It's not even clear to me if this is even a bug (as in "not working as intended"). I surely never used that pref.

Well, to me it's definitely a bug as the session is *not* restored as it was saved.  Both documents order and current document are lost (well, current document is OK if it's the first one -- and that's likely why I didn't notice very often as I usually have the same doc I come back to a lot as the first one).

And having added the feature back then, I can tell you I didn't plan for this :)

File: src/keyfile.c (hunk 1 above)
Comment (kugel-) [reply src/keyfile.c:1367]: Then I think `notebook_new_tab()` should look at `main_status.opening_session_files`. This is the primary indication that we are in "batch open mode" if some code must behave differently. I also used that flag to open docs in a idle callback instead of synchronously (see #3267 / commit 23367de0c5)

**Comment by kugel-** [comment]
> And having added the feature back then, I can tell you I didn't plan for this :)

Alright, I am convinced it's a bug now :-)

File: src/keyfile.c (hunk 1 above)
Comment (b4n) [reply src/keyfile.c]: @kugel- OK, makes sense.  Do you like it better like that (updated)?

Comment (kugel-) [reply src/keyfile.c]: yes (although I had a hard time to decode the new block in my brain)

Comment (b4n) [reply src/keyfile.c]: Yeah it required a bit of refactoring, because the previous code was a mess…

@elextr @eht16 @techee are you happy with this, and can you give this a new spin?

Comment (techee) [reply src/keyfile.c]: Nice! It:
1. Fixes the issue of the reordered tabs
2. Also opens a file from the command-line as the last tab which is much more logical than the second tab before
3. Eliminates some ugly code

The code looks good to me as well.

**Review by eht16 — APPROVED** [review]

File: src/keyfile.c (hunk 1 above)
Comment (eht16) [reply src/keyfile.c]: I had only a quick look on the code but tested it again and it works fine.

**Comment by b4n** [comment]
(I just squashed the commits and rebased on master, will now merge)

**Comment by elextr** [comment]
FFS STOP THE LAST MINUTE MERGING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

The CI ddin't even finish here.

**Comment by b4n** [comment]
@elextr regarding the CI it was merely a squash (no diff from the base verified) + a rebase… and yes, I let my build and meson finish :P  And it's all green now, ain't it :]

(though, I start to think it's becoming late indeed… I'll only plan to make one more PR for 2.0 GP :])

**Comment by elextr** [comment]
GP is less concerning, plugins can be disabled, code in Geany can't.
