### PR TITLE
Fix emission of document-activate signal and associated UI glitches

### LINKED ISSUE #3684: Wrong filename in titlebar after launch
After Geany launch a filename not corresponding to the current file is shown in the title bar - see the screenshot below. It gets fixed as active document changes. I'm wondering if something similar to https://github.com/geany/geany/issues/3609 should be also done for the titlebar.

Screenshot 2023-11-13 at 10 58 18

### PR DESCRIPTION
**Pull request by b4n**
PR https://github.com/geany/geany/pull/3267 broke handling of several special tab switch cases:

* By showing the tab's child too early, it prevented the switch-page handler to properly work in situations where there was only one page, as the tab switch would happen at page creation yet the document would not be valid yet.
* It removed explicit emission of the switch-page signal when the source and target pages are the same after session opening, which happens if the active session page is the first one.

Fix this by mostly reverting 23367de0c5237558ea63cb8c711d46390d978267 and implementing the delay directly in the switch-page handler.

Fixes #3684.

### CODE REVIEW

File: src/document.c [hunk 1]
```diff
@@ -1264,40 +1266,14 @@ void document_apply_indent_settings(GeanyDocument *doc)
...
-
-void document_show_tab_idle(GeanyDocument *doc)
-{
-	if (show_tab_idle)
-		g_source_remove(show_tab_idle);
-
-	show_tab_idle = g_idle_add(show_tab_cb, doc);
+	/* FIXME: is that actually useful??  I don't see any difference disabling this code... */
+	if (!main_status.opening_session_files)
+		document_try_focus(doc, NULL);
```
Comment (b4n) [inline src/document.c:1276]: This I don't know, I couldn't find a case where it was needed, but I guess there was a reason for it…

**Review by techee — APPROVED** [review]
Yeah, it's much better this way - the callers of `document_show_tab()` don't have to care about the details of whether it should be on idle or not and the whole logic is in one place.

Also fixes the problem of the missing `document-activate` signal from what I tested. Just to clarify, `Notebook::switch-page` is fired also for a single tab, right? The documentation isn't completely clear about it but since `document-activate` is emitted in this case, it seems to be the case.

**Comment by b4n** [comment]
> Also fixes the problem of the missing `document-activate` signal from what I tested. Just to clarify, `Notebook::switch-page` is fired also for a single tab, right? The documentation isn't completely clear about it but since `document-activate` is emitted in this case, it seems to be the case.

Yes, it is. As the docs is indeed not entirely clear, I did some empirical testing with a standalone sample app and it showed to be consistent.  And as you noted, it does work for our use-case in practice.

**Comment by b4n** [comment]
Anybody else wanting to test this?  If not, I'll merge this in a couple days and you'll all be *forced* to test it :smiling_imp:

**Comment by elextr** [comment]
Can't test, but LGBII

**Comment by b4n** [comment]
I was about to merge, but spotted a potential bug: in the unlikely case `closing_call` (that's *not* quitting, which mislead me) is set when the idle callback runs, it would fail to rested the callback ID yet remove the callback.  This could lead to failing to trigger the callback (if next run is `opening_session_files`, unlikely I guess -- didn't check), or trying to remove an invalid (or worse, reused) callback ID.

All I changed is that the ID is properly reset in this case too -- any time the callback returns `G_SOURCE_REMOVE`.

**Comment by elextr** [comment]
>  in the unlikely case closing_call

closing_all?

> it would fail to rested the callback ID

its important they are rested, we can't have tired callback IDs :grinning:
