### PR TITLE
Fix the current scope shown in the statusbar

### LINKED ISSUE #1279: Status bar showing scope: unknown unexpectedly
As pointed out by @kugel- on IRC some functions show scope "unknown" when the cursor is inside them, but they would be expected to show the function name, eg `document_open_file()`

I found it seems to be if the function declaration is more than one line, the scope shows "unknown" when the cursor is in the function body, change the declaration to one line and the scope shows correctly.

### PR DESCRIPTION
**Pull request by b4n**
Since the Scintilla C++ lexer started to fold on `()` [1], the code
looking up the current scope is confused whenever the function
signature spans multiple lines.  Fix this by resolving matching
parentheses on the candidate line before checking the fold level that
follows actually contains the current line.

Fixes #1279.

[1] https://sourceforge.net/p/scintilla/feature-requests/1138/
    imported in 24f91981c057a7e212c09da66fb974c3ccc85bd6

### CODE REVIEW

File: src/symbols.c [hunk 1]
```diff
@@ -2289,6 +2290,32 @@ static gint get_fold_header_after(ScintillaObject *sci, gint line)
 }
 
 
+/* returns the line after following all brace match for @brace on @line */
+static gint resolve_matching_braces(ScintillaObject *sci, gint line, gint brace)
+{
+	gint pos = sci_get_position_from_line(sci, line);
+	gint line_end = sci_get_line_end_position(sci, line);
+	gint lexer = sci_get_lexer(sci);
```
Comment (codebrainz) [inline src/symbols.c]: Since these are all the same type, they could be declared in the scope in which they're used (the for loop).

File: src/symbols.c [hunk 2]
```diff
@@ -2289,6 +2290,32 @@ static gint get_fold_header_after(ScintillaObject *sci, gint line)
...
+
+	for (; pos < line_end; pos++) {
```
Comment (codebrainz) [inline src/symbols.c]: Missing newline before brace

File: src/symbols.c (hunk 1 above)
Comment (elextr) [inline src/symbols.c]: Multiple declarations in the `for`? is that in the styles allowed? :smile: 

But certainly `pos` should be confined to the loop.

Comment (codebrainz) [inline src/symbols.c]: Following usually [best practices](https://www.securecoding.cert.org/confluence/display/c/DCL19-C.+Minimize+the+scope+of+variables+and+functions) they all should be really. It's not a common style in Geany yet because we only recently started using C99, but IMO we should follow this style wherever possible.

File: src/symbols.c (hunk 2 above)
Comment (elextr) [inline src/symbols.c]: This assumes the open parens is on the tag line I presume?  If so its style dependent, because C doesn't require it to be on the same line.  Maybe should look for the first open parens not assume its on the same line.

File: src/symbols.c (hunk 1 above)
Comment (b4n) [inline src/symbols.c]: Do we really want something like that?
```C

	for (gint pos = sci_get_position_from_line(sci, line),
	          line_end = sci_get_line_end_position(sci, line),
	          lexer = sci_get_lexer(sci); pos < line_end; pos++)
```

I mean, sure in theory scoping is best, but here IMO it makes this harder to read, and the parent scope doesn't contain anything anyway, so it's not mixed with other stuff.  If it was a `size_t i`, sure, but here I'm not convinced.

File: src/symbols.c (hunk 2 above)
Comment (b4n) [inline src/symbols.c]: @codebrainz indeed, will fix

Comment (b4n) [inline src/symbols.c]: @elextr
> does this need to be a separate function?

No, I initially wrote it inside `get_current_tag_name()`'s body, but it seemed like a contained enough logic to be worth wrapping in a logical container (the function).  I can un-split it if you want, but it seemed slightly less nice to me there.  But admittedly I'm an advocate of splitting up logical units when the reader can then see it as that logical unit ("this search for the line on which unmatched parentheses on `@line` are all matched") and can avoid caring about the implementation, or find a implementation issue in the logic there rather than in the context of a whole other set of stuff -- but yes, I do think there is such thing as over-splitting, too (basically when it ends up in split things that don't have a defined goal by themselves).

> its style dependent, because C doesn't require it to be on the same line. Maybe should look for the first open parens not assume its on the same line.

That's a good point, but would be slightly more subtle to fix.  Though maybe not so much, just check each fold level between the tag and the containing one and see if it matches parentheses matching, and skip it if so.  I'll give it a look.

File: src/symbols.c (hunk 1 above)
Comment (elextr) [inline src/symbols.c]: @b4n, IMHO declare pos in the loop, its the loop iterator, thats a common paradigm.

File: src/symbols.c (hunk 2 above)
Comment (elextr) [inline src/symbols.c]: > but yes, I do think there is such thing as over-splitting, too (basically when it ends up in split things that don't have a defined goal by themselves).

Its always a judgement call, and it depends critically on the name of the function being obvious, otherwise everybody has to go "oh, `resolve_brace_match` hmmm, what does that do? what does "resolve" mean in this context? I guess I better go find its definition and read it.  Which is a waste of everybodys time instead of having a few extra lines in the function, which you can even comment :)

**Comment by b4n** [comment]
Rewritten differently to address the issue where it only solved the case where the argument list starts on the tag line (which is highly likely, but not guaranteed) as per @elextr comment.

Now, it skips fold levels that look like being introduced by parentheses.  It might be slightly problematic if a language doesn't fold on parentheses yet has a fold level that so happens to match perfectly just as if it did.  I doubt we would see that, but if it's a problem we could restrict the extra checks to `LexCPP` (or any other that folds on `()`).

**Comment by elextr** [comment]
LGBI

File: src/symbols.c (hunk 1 above)
Comment (codebrainz) [inline src/symbols.c]: > Do we really want something like that?

Looks OK to me, what's hard to read about it?

Comment (codebrainz) [inline src/symbols.c]: > IMHO declare pos in the loop, its the loop iterator, thats a common paradigm

Declaring the loop terminator in it is also common.

Comment (b4n) [inline src/symbols.c]: > Looks OK to me, what's hard to read about it?

I find this overlong precondition hides the logic of the loop (condition and post-body).

Anyway, the new code is different, do you still think I should so something like that now the 2 other variables are constant?

Comment (elextr) [inline src/symbols.c]: @b4n, agree that them being const is correct, and assists the compiler (and human) in understanding your intention.  Its not possible to do that in the initialiser if `pos` is non-const, so better out of it.

Comment (elextr) [inline src/symbols.c]: `const` is good, `const` should be used more :-D

That said, nobody should sit down and add it to existing code, just use it on new code when you can.

Modifying existing code can be problematical, passing a `const` to existing functions with non-const parameters would cascade `const` changes everywhere through code that didn't need to be modified.  So its not worth it to change old code unless its local only.

Comment (codebrainz) [inline src/symbols.c]: I propose something like the following changes to `HACKING`:

```diff
diff --git a/HACKING b/HACKING
index 938688d..13e4025 100644
--- a/HACKING
+++ b/HACKING
@@ -200,8 +200,18 @@ Coding
   moment, we want to keep the minimum requirement for GTK at 2.24 (of
   course, you can use the GTK_CHECK_VERSION macro to protect code using
   later versions).
-* Variables should be declared before statements. You can use
-  gcc's -Wdeclaration-after-statement to warn about this.
+* Variables should be declared (and initialized) as close as practical
+  to their first use. This reduces the chances of intervening code being
+  inserted between declaration and use, where the variable may be
+  uninitialized.
+* Variables should be defined within the smallest scope that is practical,
+  for example inside a conditional branch which uses them or in the
+  initialization part of a for loop.
+* Local variables that will not be modified should be marked as ``const``
+  to indicate intention. This allows the compiler to give a warning if
+  part of the code accidentally tries to change the value. This does not
+  apply to by-value parameters where it needlessly exposes the
+  implementation and it's obvious a copy is made anyway.
 * Don't let variable names shadow outer variables - use gcc's -Wshadow
   option.
 * Do not use G_LIKELY or G_UNLIKELY (except in critical loops). These
```

Comment (elextr) [inline src/symbols.c]: Looks basically ok.  Can you make a PR for the HACKING changes instead of it being a comment on an outdated commit on an unrelated PR :)

Comment (codebrainz) [inline src/symbols.c]: I can, I just wanted to see what you guys thought before making a PR that will have to be changed a bunch of times, and put it here with the current discussion (which is available in the comments mailing list for posterity and emailed to anyone interested as well) rather than spreading it all over.

Comment (codebrainz) [inline src/symbols.c]: See #1282

**Comment by elextr** [comment]
Quick test seems to work.

**Comment by b4n** [comment]
Didn't I merge that already?  damned, I didn't.

**Comment by kugel-** [comment]
Thanks 🥇
