### PR TITLE
C, C++, C#, D: Improve return type and var type recognition

### LINKED ISSUE #845: Function return types truncated in C++
Example (compiles and runs):

```c++
#include <string>
#include <iostream>

std::string f(){
    return std::string("abc");
};

int main(int, char **)
{
	std::cout<<f()<<std::endl;
	return 0;
}
```

The return type for `f()` shown in the symbol bar tooltip and the editing window tooltip (when you type `f(` ) only shows the `std` not `std::string`.

~~This is a regression, it used to be correct.~~

### PR DESCRIPTION
**Pull request by b4n**
This is far from perfect and contains a lot of guessing.  It showed
good results based on our tests cases, fixing several issues and not
introducing any more issues (admittedly, after working around a subtle
one regarding D static ifs).

Closes #845.

### CODE REVIEW

**Comment by b4n** [comment]
@elextr please look, check, tests and see it's a little less wrong than before :)

**Comment by b4n** [comment]
@techee thanks!  Beware, it contains its fair share of hacks (it's c.c, so no surprise).

It's so much of a mess I almost seriously considered trying to rewriting if from scratch, properly split and everything.  I'm pretty sure in the end it would save me time, instead of fixing this again and again, with low confidence on the impacts each iteration can have…

File: tests/ctags/var-and-return-type.cpp [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+const type1_t func3();
+const type1_t var3 = { 0, 0 };
+
+struct type1 func4();
+struct type1 var4 = { 0, 0 };
+
+type1_t func5();
+type1_t var5 = { 0, 0 };
+
```
Comment (elextr) [inline tests/ctags/var-and-return-type.cpp]: what about testing  `type1_t var{};` or `type1_t var{ 0, 0 };`

what about testing `auto func()->type1_t` C++11 syntax

Comment (b4n) [inline tests/ctags/var-and-return-type.cpp]: > what about testing  `type1_t var{};` or `type1_t var{ 0, 0 };`

Nothing to do with reporting the var type, it's "just" another mean of initializing.  So different issue, possibly different test case.

> what about testing `auto func()->type1_t` C++11 syntax 

This is more related, but still quite outside the scope here, as AFAIK `->` syntax is not supported at all yet. (OT, WTF is about this syntax?  why add a new one?)

Comment (elextr) [inline tests/ctags/var-and-return-type.cpp]: > Nothing to do with reporting the var type, it's "just" another mean of initializing. So different issue, possibly different test case.

Fair enough

> AFAIK -> syntax is not supported at all yet.

For some reason I thought it was, maybe another language.

> (OT, WTF is about this syntax? why add a new one?)

So it is after parameter declaration and so can use decltype(parameter) where the parameter type is from a template parameter and so not known until template parameter deduction.

File: tagmanager/ctags/c.c [hunk 2]
```diff
@@ -1254,40 +1256,90 @@ static void addOtherFields (tagEntryInfo* const tag, const tagType type,
...
+	switch (st->declaration) {
+		case DECL_BASE:
+		case DECL_FUNCTION:
+		case DECL_FUNCTION_TEMPLATE:
+			break;
+		default:
+			return vStringValue(st->firstToken->name);
+	}
 
 	if (vt == NULL)
```
Comment (techee) [inline tagmanager/ctags/c.c]: vt seems to be always NULL (not really related to your changes).

File: tagmanager/ctags/c.c [hunk 3]
```diff
@@ -1254,40 +1256,90 @@ static void addOtherFields (tagEntryInfo* const tag, const tagType type,
...
+
+		/* stop if we find the token used to generate the tag name, or
+		 * a name token in the middle yet not preceded by a scope separator */
+		if ((t == nameToken ||
+		     (t->type == nameToken->type &&
+		      t->keyword == nameToken->keyword &&
+		      t->lineNumber == nameToken->lineNumber &&
+		      strcmp(vStringValue(t->name), vStringValue(nameToken->name)) == 0)) ||
+		    (t->type == TOKEN_NAME && seenType &&
+		     (i > 0 && st->token[i - 1]->type != TOKEN_DOUBLE_COLON)))
```
Comment (techee) [inline tagmanager/ctags/c.c]: Just for my information, what do the two lines check? Or in other words, what would happen if the check was missing and we always ended at nameToken? (I don't completely understand the comment above.)

Comment (techee) [inline tagmanager/ctags/c.c]: OK, is it to strip away templates? Maybe we could keep them here and remove them in the strip_type() function in TM. On the other hand one usually doesn't want to see the multiline templates from std:: at all :-)

**Comment by techee** [comment]
@b4n I had a brief look at the patch and it good. Well, can't say I really get the subtle things but the overall logic looks good and the test results look good too.

**Comment by techee** [comment]
@b4n I'm wondering if it wouldn't be easier not to process the tokens for var_type but just the raw input similarly to getArglistFromFilePos() and stripping away comments, newlines and double-spaces. This seems to be a similar case. But I may miss something.

**Comment by techee** [comment]
OK, thinking about it more by just recording the string we wouldn't strip away things like public/private/... which aren't really a type. So yeah, I guess the current approach is right.

File: tagmanager/ctags/c.c (hunk 2 above)
Comment (b4n) [inline tagmanager/ctags/c.c]: no, it's `static` (which is meh, but well)

File: tagmanager/ctags/c.c (hunk 3 above)
Comment (b4n) [inline tagmanager/ctags/c.c]: No, the point is to not include e.g. the class name in `std::string myclass::do_something();`.
The idea is fairly simple: when I see a name not preceded by a double colon (e.g. not simply qualified), and I already found something looking like a type (either a custom name, or a data type keyword (`void`, `int`, etc.)), I assume it's not part of the type anymore.

Maybe I miss some legitimate cases I don't know about, and yeah, it might lead to also ignoring template types (but it already did before, so it might be unrelated and that might just not show in the statement's tokens).

**Comment by b4n** [comment]
@techee well, maybe… but honestly I'm not sure how I'd do that, nor if it didn't indeed produce a lot of uninteresting stuff that'd be just as hard to cleanup.  And it doesn't solve the problem of "how do I know where the return type starts and ends" :)

File: tagmanager/ctags/c.c (hunk 3 above)
Comment (elextr) [inline tagmanager/ctags/c.c]: @b4n 

will `typename foo<t1, t2>::a type qualifier::func()` work?

Comment (b4n) [inline tagmanager/ctags/c.c]: Probably not, gives type `typename foo::a` (to `qualifier::func()` function).

Maybe `typename` could be handled specially if needed?
Or maybe another solution, like finding the name token first, and then going back to skip the possible qualifier, might give better results?  it's what I first tried and it was a mess, but maybe it could be made to work.

Comment (elextr) [inline tagmanager/ctags/c.c]: @b4n, did you get the version with my typo fixed? (damn github for not notifying edits)

Comment (b4n) [inline tagmanager/ctags/c.c]: ah, no, I was too quick :)  I picked it on the webpage so it ain't github's fault this time, but no I used the version with the space.

Your corrected example gives type `typename foo::a_type` (which looks more or less correct to my innocent eyes, except for the stripped `<>`, which I believe is an issue of what gets put in the statement's token list).

File: tagmanager/ctags/c.c (hunk 2 above)
Comment (techee) [inline tagmanager/ctags/c.c]: Uh, right, I missed that.

File: tagmanager/ctags/c.c (hunk 3 above)
Comment (techee) [inline tagmanager/ctags/c.c]: @b4n Thanks for the clarifications - the code looks good to me and seems to work fine in most cases.

Comment (elextr) [inline tagmanager/ctags/c.c]: @b4n, leaving out the template parameters is sort of bad, they really are part of the type.  Makes it quite long of course, but showing `std::map` for `std::map<std::string, std::pair<std::string, int>>` is missing a lot of information.

Also another test that has parens and semi-arbitary expressions in the type :)

```
    decltype(std::declval<type_with_member_function_foo>().foo()) n2 = n1;
```

I am assuming trying these sorts of things now is better than waiting until you finish and then point out something else missing :)

Comment (techee) [inline tagmanager/ctags/c.c]: @elextr I'm afraid that proper template parsing would double the c.c size and would take a really lot of time to develop. The only possibility to have templates in the type is to really just record the input string together with some reasonable begin/end type detection. But even this will probably require quite some work and the question is whether it's worth it.

The implementation in this patch is good enough IMO - at least for the scope completion where we'd have to remove the templates anyway.

Comment (elextr) [inline tagmanager/ctags/c.c]: To summarise our IRC discussion while github was down.

@b4n is concerned about the template params in autocompletion, I'm concerned about them in the tooltips.  Maybe those need to be separate things, with the tooltip being just a copy of the relevant part of the source as suggested above.  

BTW I am not suggesting parsing the parameters, I don't want compiler like situations where `std::string` is expanded to `std::basic_string<char, traits blah blah>`.

The decltype example fails as expected.

Comment (b4n) [inline tagmanager/ctags/c.c]: > @b4n is concerned about the template params in autocompletion, I'm concerned about them in the tooltips.

I'm not really concerned about one side or the other, just about reporting something relevant.  Actually, I'd rather be concerned by reporting relevant tooltips, and then when it works figure out how the heck we can use that for completion.

> Maybe those need to be separate things, with the tooltip being just a copy of the relevant part of the source as suggested above. 

Indeed, maybe.  Though, I tried to "just [make] a copy of the source", and it seems a lot easier said than done, because for some reason the token's position don't seem to be really correct and I get more or less garbage that way.  I dropped it after pulling my last hair.  I might give it another shot when they have grew back :)

Comment (techee) [inline tagmanager/ctags/c.c]: @b4n I agree - it's fine the way it is. What about merging this plus the bloody scope completion patch set so the whole thing is over? I'd like to push some related patches like autocompletion for namespaces plus some cleanup patches but I'd like to have it on top of master with scope completion in.

Comment (b4n) [inline tagmanager/ctags/c.c]: I'm actually on it right now, should pop up in master anytime now :)

Comment (techee) [inline tagmanager/ctags/c.c]: Yay, great!!!
