### PR TITLE
Use pre-compiled 'grep' binary from MSYS2 on Windows

### LINKED ISSUE #1229: Geany 1.28 "Find in files" doesn't work in Windows 7 64bit OS
Please check screenshot(attached
screenshot - sep 12 2016 8 11 am
) and let me know what could be issue responsible for this behaviour.

Ask me if still not clear.

### PR DESCRIPTION
**Pull request by eht16**
This drops the self-compiled 'grep' version which caused issues
with recursive searches on Windows as well as with non-ASCII
characters in paths.
The pre-compiled 'grep' binary from MSYS2 (matching the target ABI)
seems to solve probably all of the known problems on Windows.
The only drawback is that we need to ship a few additional MSYS2
libraries on which the 'grep' binary depends.

Closes #1229 and #1260.

### CODE REVIEW

**Comment by kugel-** [comment]
Did you make sure that that grep doesn't link to the msys2 runtime?

**Comment by kugel-** [comment]
Nevermind, msys2 runtime is required. Not a fan of shipping those, tbh.

**Comment by eht16** [comment]
Yes, it is required and included. And yes, I don't like this not that much too. But the alternatives (I know of) are not much better.
At some day, @codebrainz will implement FiF completely in C without external tools and then things will get better.

File: scripts/gtk-bundle-from-msys2.sh [hunk 1]
```diff
@@ -212,6 +212,10 @@ copy_grep_and_dependencies() {
 	if [ "${own_arch}" == "${ABI}" -o -z "${MSYS2_ABI_PATH}" ]; then
 		bin_dir="/usr/bin"
 	else
+		# TODO we could maybe download MSYS2 from http://www2.futureware.at/~nickoe/msys2-mirror/distrib/
+		# extract the relevant files, download "grep" from
+		# http://www2.futureware.at/~nickoe/msys2-mirror/msys/${ABI}/grep-2.XX-1-${ABI}.pkg.tar.xz
+		# and so automate this even more than requiring an existing separate MSYS installation
```
Comment (kugel-) [inline scripts/gtk-bundle-from-msys2.sh]: I think this comment is weird. The script is meant to be run from an MSYS2 shell.

Besides, you can use pacman to download the archive files, the other parts of the bundle script do that.

Comment (eht16) [inline scripts/gtk-bundle-from-msys2.sh]: Yeah, but usually we build for the target ABI i686 and on my system MSYS2 is x86_64. If I would use grep.exe from my MSYS2 shell, it would be x86_64 and so not usuable for users with a 32bit Windows system.

But yeah, maybe we can even pull the dependencies from Pacman instead. I will have a look at this post-1.29.

**Comment by eht16** [comment]
@kugel- I reworded the comment and squashed the commits.

**Comment by b4n** [comment]
I kind of agree with @kugel- that linking and distributing libmsys2 isn't pretty, but if it fixes both issues I think it's worth it.  How heavier is the installer with this?

Anyway, your call but I think it's OK.

**Comment by eht16** [comment]
Size overhead unpacked:  4.9M
Size overhead packed (installer): 1.15 MB

As said, I don't like redistributing MSYS2 runtime too. It's still the best option I see currently.

**Comment by b4n** [comment]
Okay, so go for it I think.
