### PR TITLE
Restore startup behavior to focus files from the command line after session files

### LINKED ISSUE #3210: Geany doesn't switch to newly opened document when restoring previously opened files
When "load files from the last session" is enabled, regardless of whether a project is loaded, the previously active document is reactivated when Geany is closed and restarted with a document at the command line or from a file manager.  The expected behavior is to activate the newly opened document for editing.  When Geany is open in the background, it switches to the new document, as expected.

This occurs with the default config and no plugins loaded.  Does not occur in an old build from 2021-12-30.  Does occur in builds dated after 2022-05-01.  I did not build Geany between those dates, so don't know when the new behavior was introduced.  I do not see it in the manual, nor do I see any option to revert to the old behavior.

To reproduce:

1. Open Geany.
2. Open several documents.
3. Close Geany.
4. Open Geany with a file from a file manager or command line.
5. Geany will open and activate the last active document.  Expected behavior is to activate the newly opened document for editing.

### PR DESCRIPTION
**Pull request by kugel-**
PR #3125 (commit 22aac443) broke that accidentally by moving the
"switch to last used tab" to a idle callback (g_idle_add()). This
runs after opening files from the command line.

Now, the same callback is moved to libmain.c and is only registered
when there are no files from the command line.

Additionally, projects gains a private copy of the current_page loaded
from the keyfile.

Fixes #3210

### CODE REVIEW

**Comment by eht16** [comment]
Looks fine.
The notebook page is properly saved and restored across Geany restarts, also for projects, even independently. Great.

While testing I noticed one minor issue though I'm not sure whether it's new or not:
when I close a project, the previous session is restored but the "current_page" setting is ignored and not restored.

Similarly, when opening a project, the project specific "current_page" setting is ignored.

**Comment by kugel-** [comment]
Seems to be a regression of this patch. I'm looking at it.

**Comment by ntrel** [comment]
Haven't looked at this, but it may be affected by #3395.

File: src/editor.c [hunk 1]
```diff
@@ -4746,8 +4746,12 @@ gboolean editor_goto_pos(GeanyEditor *editor, gint pos, gboolean mark)
 	sci_goto_pos(editor->sci, pos, TRUE);
 	editor->scroll_percent = 0.25F;
 
-	/* finally switch to the page */
-	document_show_tab(editor->document);
+	/* switch to the page, via idle callback in case of batch-opening */
+	if (main_status.opening_session_files)
+		document_show_tab_idle(editor->document);
```
Comment (eht16) [inline src/editor.c:4751]: Maybe we can use `document_show_tab_idle()` unconditionally even for non-batch-opening?

I didn't test but would assume it behaves equally.

**Comment by eht16** [comment]
> Haven't looked at this, but it may be affected by #3395.

I just tested the latest changes and it seems fine for me now.
Had only a minor remark but it is not critical at all.

File: src/editor.c (hunk 1 above)
Comment (kugel-) [reply src/editor.c:4751]: I thought about it but I hesitated because I wasn't sure if someone (like a plugin) depends on `document_get_current()` returning the switched-to doc immediately after using calling `document_show_tab()` or document_open_*. This also affects the document_open_* functions which internally call `document_show_tab()` via `editor_goto_pos()`.

**Comment by eht16** [comment]
Fine by me to merge.
