### PR TITLE
Remove native file and color dialogs on Windows

### LINKED ISSUE #3209: Geany crashes when opening many files at once
When opening many files at once by selecting them in the file open dialog on windows 10, geany simply crashes to the desktop with no message at all.

I don't know the exact number of files, but I'm sure that under 10 files it never happens, and over 30 files it always happens.

### PR DESCRIPTION
**Pull request by eht16**
Their implementation was buggy, use very old Windows APIs and require
double implementation and maintenance efforts for us
The GTK dialogs work well for all other users already, so they probably
will also for Windows users.

Closes #3209.

### CODE REVIEW

File: src/ui_utils.h [hunk 1]
```diff
@@ -63,7 +63,7 @@ typedef struct GeanyInterfacePrefs
 	gboolean		msgwin_compiler_visible;	/**< whether message window's compiler tab is visible */
 	gboolean		msgwin_messages_visible;	/**< whether message window's messages tab is visible */
 	gboolean		msgwin_scribble_visible;	/**< whether message window's scribble tab is visible */
-	/** whether to use native Windows' dialogs (only used on Windows) */
+	/** whether to use native Windows' dialogs - ignored and not used anymore */
```
Comment (eht16) [inline src/ui_utils.h:66]: Since this field is part of the API (and ABI), we cannot easily remove it.

Is it enough to mark it as ignored in the comment or are there better ways to handle this?

Comment (elextr) [reply src/ui_utils.h:66]: I would suspect that there are not many Windows specific plugins out there, so probably ok.

Comment (elextr) [reply src/ui_utils.h:66]: Actually so long as it is still initialized to say "Windows dialogs not used" then its definitely ok.

File: src/dialogs.c [hunk 2]
```diff
@@ -460,27 +461,20 @@ void dialogs_show_open_file(void)
...
+	if (initdir != NULL && g_path_is_absolute(initdir))
+			gtk_file_chooser_set_current_folder(GTK_FILE_CHOOSER(dialog), initdir);
 
-		if (initdir != NULL && g_path_is_absolute(initdir))
-				gtk_file_chooser_set_current_folder(GTK_FILE_CHOOSER(dialog), initdir);
+	if (app->project && !EMPTY(app->project->base_path))
+		gtk_file_chooser_add_shortcut_folder(GTK_FILE_CHOOSER(dialog),
+				app->project->base_path, NULL);
 
-		if (app->project && !EMPTY(app->project->base_path))
```
Comment (elextr) [inline src/dialogs.c:476]: Why is adding this shortcut removed?

Comment (elextr) [reply src/dialogs.c:476]: Bah!! ignore comment, githubs annoying handling of changed indent confused me.

**Review by elextr — APPROVED** [review]

**Comment by elextr** [comment]
Just remembered that there was #2794 that was "fixed" by using native dialogs once after install?

File: src/dialogs.c (hunk 2 above)
Comment (eht16) [reply src/dialogs.c:476]: Yeah, sorry. The diffs are bit hard to read because of indentation changes :(:

File: src/ui_utils.h (hunk 1 above)
Comment (eht16) [reply src/ui_utils.h:66]: It's not initialized explicitly at all. But at least on my Debian Testing, the resulting value when Geany is running is `FALSE`.

**Comment by eht16** [comment]
> Just remembered that there was #2794 that was "fixed" by using native dialogs once after install?

Yes. This PR is the most easiest solution to solve the one problem in #3209.
Fixing the dialog crash or even better port the Windows native code to more modern APIs would be far better without a doubt. But I won't do this (not only because after I would have done there were probably more bugs in the code than before :D).
For me, it's a trade-off how to spend the available time (as usual and as you most probably agree on).

I'm happy to close this PR unmerged if we could find anyone else volunteering to do the good way.

**Comment by elextr** [comment]
> I'm happy to close this PR unmerged if we could find anyone else volunteering to do the good way.

If it wasn't that #3209 is a crash I'd say leave the windows dialogs until GTK4 forces them out, after all they have been used for a long time without issues.  

But since its a crash I'd say merge it, if any white knight rides in on their trusty steed I suspect the olde code would not be much help since the Windows dialog APIs have changed, but they can always choose to start with the commit before merge of after, their choice.

Or perhaps someone will try https://docs.gtk.org/gtk3/class.FileChooserNative.html and see if it works better on windows/macos and flatpack (see docs).

**Comment by kugel-** [comment]
Interesting, didn't know about GtkFileChooserNative. This seems to be available in gtk4 as well.

**Comment by eht16** [comment]
If nobody stops me, I would merge this in a week or so.
This should not hinder any experiements with GtkFileChooserNative at all.

**Comment by djhenderson** [comment]
This is a show stopper for upgrading to 2.0. The GTK open file dialog is trash for a regular windows user. There is no longer a way to open an explorer window OOB.

**Comment by djhenderson** [comment]
I suspect those dialog  are crashing because you are not passing the right memory allocator to them, perhaps without the right memory options, eg. not requesting global shared, instead of default scope. Not you directly perhaps, but the GTK code.

**Comment by elextr** [comment]
To be clear, there have been no contributions by Windows users and the previous Windows dialog code related to a crash.  Since no Windows contributors addressed the problem, the only option the non-windows contributors had was to remove the windows related code to avoid the crash.

Perhaps "somebody" could try GtkFileChooserNative as was mentioned above, but again none of the Geany contributors use Windows.

**Comment by b4n** [comment]
Isn't the question rendered moot by #3861? It's gonna be in 2.1, whenever that's released.

**Comment by elextr** [comment]
Didn't umm, thingy, you know, whatchamacallit .. oh yeah, remember. ;-)

**Comment by djhenderson** [comment]
Thanks for the info. I found  a recent 2.1 CI build artifact to install. It restores the familiar windows native file dialogs. It works great, so I am going to use it going forward.

Is there anyone out there who has built Geany on a real Windows box with MSYS2 installed? I am thinking about trying that again (I tried with 1.35 or so, IIRC).

**Comment by eht16** [comment]
Here is one but I'm not proud of it :).

There is also a howto on https://wiki.geany.org/howtos/win32/msys2.

It might be easier to choose the latest CI build from https://github.com/geany/geany/actions/workflows/build.yml?query=event%3Apush+branch%3Amaster and download the installer from the artifacts section.

For further questions and comments, it'd be if you could open a new discussion or issue.
