### PR TITLE
Fix undo of line end type change

### LINKED ISSUE #409: Undoing Document->"Set line endings" doesn't undo the line ending flag
I've been playing with the global menu integration on OS X and clicking around a lot to find all possible problems and one issue I have noticed is that if you perform Document->"Set line endings" and undo this change, the changed line ending type stays at the changed line endings (the actual line ending change is undone correctly).

I think we should do something similar to e.g. encoding change which has a special handling in document_undo() and document_redo().

I'll have a look at it unless someone is faster.

### PR DESCRIPTION
**Pull request by techee**
At the moment undo of line end type change only undos the changes made
in the document but the different line ending settings remains active.

This patch fixes the issue by combining the line end scintilla undo action
with a new UNDO_EOL action responsible for updating the line ending
settings.

Fixes #409

### CODE REVIEW

File: src/ui_utils.c [hunk 1]
```diff
@@ -1022,6 +1022,24 @@ void ui_sidebar_show_hide(void)
...
+	{
+		case SC_EOL_CR: widget_name = "cr"; break;
+		case SC_EOL_LF: widget_name = "lf"; break;
+		default: widget_name = "crlf"; break;
+	}
+	gtk_check_menu_item_set_active(
+		GTK_CHECK_MENU_ITEM(ui_lookup_widget(main_widgets.window, widget_name)), TRUE);
+
+	ui_update_statusbar(doc, -1);
+}
```
Comment (b4n) [inline src/ui_utils.c]: is splitting this out of `ui_document_show_hide()` worth it?  It's a mere optimization IIUC, but it requires the caller to play with `ignore_callback`, and it calls `ui_update_statusbar()` which wasn't done previously in `ui_document_show_hide()`, so many callers do both themselves.

So my question is, why not simply call `ui_document_show_hide()` from the undo stuff, and not care about it updating more than it needs to?

BTW, if we want to be able to nest calls playing with `ignore_callback`, we could make it an integer and `++` and `--` it instead of setting to absolute `TRUE`/`FALSE`.  Though ideally one day we get rid of that odd global.

**Comment by b4n** [comment]
Apart that, LGBI

File: src/ui_utils.c (hunk 1 above)
Comment (techee) [inline src/ui_utils.c]: There was nothing really deep behind this - just pure laziness - I basically just copied what was in UNDO_ENCODING. Looking at it you are right, this is unnecessary.

To make things consistent I added a similar patch for UNDO_ENCODING too.

**Comment by techee** [comment]
Meh, travis seems to be in a bad mood today. Builds fine here.

**Comment by b4n** [comment]
> Meh, travis seems to be in a bad mood today.

Yeah apparently some repositories it uses are down.
