### PR TITLE
Fix wrong format specifier in debug message

### LINKED ISSUE #2639: geany would not open (Windows 10)
so i recently installed geany since visual studio was too long to install but
after i finished setup, i clicked on the shortcut but it would not open,
i tried to run geany from the start menu, even from e: (the drive i installed geany on) but nothing would work
i have the gtk+ runtime thing installed. i tried it from wsl, but still nothing.
can someone help me? thanks

### PR DESCRIPTION
**Pull request by eht16**
This led to crashes on Windows when starting without an existing
configuration file.

Closes #2639.

### CODE REVIEW

File: src/libmain.c [hunk 1]
```diff
@@ -406,7 +406,7 @@ static gint get_windows_socket_port(void)
 	if (! g_file_test(configfile, G_FILE_TEST_IS_REGULAR))
 	{
 		geany_debug(
-			"No user config file found, use default TCP port (%s).",
+			"No user config file found, use default TCP port (%d).",
```
Comment (elextr) [inline src/libmain.c:409]: Minor English improvement s/use/using/

Comment (eht16) [reply src/libmain.c]: Thanks, I went a bit further and made the text more similar to the other message text below. Still OK?

File: src/libmain.c [hunk 2]
```diff
@@ -406,7 +406,7 @@ static gint get_windows_socket_port(void)
 	if (! g_file_test(configfile, G_FILE_TEST_IS_REGULAR))
```
Comment (b4n) [inline src/libmain.c:406]: This code could actually be simplified by basically having the same code path for the with and without config cases: just don't load the config if it doesn't exist, and then `utils_get_setting_integer()` will return the default.  But that's not for a point release.

**Review by b4n — APPROVED** [review]
LGTM.  Changing the wording might be good and I'm not against it here, but as a rule of the thumb I usually prefer to avoid unnecessary changes in bugfix releases.

**Comment by eht16** [comment]
> LGTM. Changing the wording might be good and I'm not against it here, but as a rule of the thumb I usually prefer to avoid unnecessary changes in bugfix releases.

Yeah, right you are.
What about cherry-picking 3ab2518 into the `1.37` branch, update NEWS et. al and release.
In this PR we could then afterwards simplify the code as suggested for 1.38+.

File: src/libmain.c (hunk 1 above)
Comment (elextr) [reply src/libmain.c]: Ok.

**Comment by b4n** [comment]
> What about cherry-picking [3ab2518](https://github.com/geany/geany/commit/3ab2518bc254994ea7fd789eda721f9514210e40) into the `1.37` branch, update NEWS et. al and release.
> In this PR we could then afterwards simplify the code as suggested for 1.38+.

Sounds good to me.  I prep'd the 1.37 branch you created, and cherry-picked the first commit you mentioned.  I won't do the whole release stuff tonight, but probably doable tomorrow.

File: src/libmain.c (hunk 2 above)
Comment (eht16) [reply src/libmain.c]: Done in 58c5e34a3b3763bd0f22152a6df02db68bd7c8ab

**Review by b4n — APPROVED** [review]
LGTM, and I trust you have actually tested this on Windows, with and without initial config :wink:

**Comment by eht16** [comment]
> I trust you have actually tested this on Windows, with and without initial config wink

Oh yes. I'm constantly trying to do the same mistake only once :).
