### PR TITLE
SaveActions: Add configurable target directory for instantly saved files

### LINKED ISSUE #640: Loading temporary files from the last session at startup does not work after a server reboot
Hello,

Unfortunately my linux distribution (Fedora 22) and gnome are not as stable as I would want them to be and every now and then gnome or the server crashes...

Then all the temporary files in "/tmp" are lost. When geany is started again after a relaunch it tries to open these recently open files automatically but of course it does not find them.

I know about the backup plugin in but it is not as convenient, because geany does not try reopen the temporary files from the backup location, if it does not find the files under /tmp anymore.

Thus my alternative suggestions:
1) Make the temporary file location configurable so that one can set it to e.g. /reboot-stable/tmp
2) Let geany fallback to look for recently open files in the backup location if they are not found in /tmp
anymore.

The objective is that: After a crash and a wiped tmp dir geany would still be able to continue where it was stopped: All recently open temporary files would be reopened and the user could simple continue to use it.

As it is now the promise suggested by the startup option "Load files from the last session", is not kept (when it is mosed needed). 

Thank you for this great program and all your efforts! - best, Robert

### PR DESCRIPTION
**Pull request by eht16**
Closes #640.

ead067b fixes an unrelated bug I noticed while testing: if filetype "None" or another filetype without an extensions was chosen, the created temporary filename had a trailing dot.

### CODE REVIEW

File: plugins/saveactions.c [hunk 1]
```diff
@@ -91,11 +93,17 @@ static gchar *config_file;
...
- * set backup_dir to the locale encoded form of utf8_dir */
-static gboolean backupcopy_set_backup_dir(const gchar *utf8_dir)
+ * set target to the locale encoded form of utf8_dir */
+static gboolean store_target_directory(const gchar *utf8_dir, gchar **target)
 {
 	gchar *tmp;
 
+	if (target == NULL)
+	{
+		SETPTR(*target, NULL);
```
Comment (elextr) [inline plugins/saveactions.c:103]: `*target` is guaranteed to dereference a NULL?????

File: plugins/saveactions.c [hunk 2]
```diff
@@ -260,11 +268,14 @@ static void instantsave_document_new_cb(GObject *obj, GeanyDocument *doc, gpoint
...
 		gchar *new_filename;
 		gint fd;
 		GeanyFiletype *ft = doc->file_type;
 
-		fd = g_file_open_tmp("gis_XXXXXX", &new_filename, NULL);
+		directory = !EMPTY(instantsave_target_dir) ? instantsave_target_dir : g_get_tmp_dir();
+		new_filename = g_build_filename(directory, "gis_XXXXXX", NULL);
+		fd = g_mkstemp(new_filename);
 		if (fd != -1)
 			close(fd); /* close the returned file descriptor as we only need the filename */
```
Comment (elextr) [inline plugins/saveactions.c:281]: If g_mkstemp() returns -1 is the filename valid and usable?

Comment (elextr) [reply plugins/saveactions.c:281]: Also since g_mkstemp() makes a file the now non-temporary file directory gets two files, for example `gis_setv00` and `gis_setv_00.c`.

**Review by elextr — COMMENTED** [review]
One new bug and two things I noticed in the original.

**Comment by elextr** [comment]
Not part of this PR, but related, how is it possible to create a new file with no filename but a filetype that is not none?  Using `New (with template)` gives the new file a name `untitled.ext` so it doesn't instant save, is that intended?.

File: plugins/saveactions.c (hunk 1 above)
Comment (eht16) [reply plugins/saveactions.c]: This didn't make sense. Thanks for the pointer.
I rewrote the code to return `FALSE` as it should no valid case when the target variable is `NULL`.

File: plugins/saveactions.c (hunk 2 above)
Comment (eht16) [reply plugins/saveactions.c]: > If g_mkstemp() returns -1 is the filename valid and usable?

As per docs, no. So we handle now errors by showing them to the user and cancelling Instant Save.



> Also since g_mkstemp() makes a file the now non-temporary file directory gets two files, for example `gis_setv00` and `gis_setv00.c`.

Good catch! Fixed by first constructing the final filename and then call `g_mkstemp()` to have the file created.

**Comment by eht16** [comment]
> Not part of this PR, but related, how is it possible to create a new file with no filename but a filetype that is not none? Using `New (with template)` gives the new file a name `untitled.ext` so it doesn't instant save, is that intended?.

I don't remember all cases where new files with a filetype set are created, there were many combinations.

File: plugins/saveactions.c [hunk 3]
```diff
@@ -260,23 +262,36 @@ static void instantsave_document_new_cb(GObject *obj, GeanyDocument *doc, gpoint
...
 			 * configured default file type */
 			ft = filetypes_lookup_by_name(instantsave_default_ft);
 
-		if (ft != NULL)
-			/* add the filetype's default extension to the new filename */
+		/* construct filename */
+		directory = !EMPTY(instantsave_target_dir) ? instantsave_target_dir : g_get_tmp_dir();
+		new_filename = g_build_filename(directory, "gis_XXXXXX", NULL);
+		if (ft != NULL && !EMPTY(ft->extension))
 			SETPTR(new_filename, g_strconcat(new_filename, ".", ft->extension, NULL));
```
Comment (elextr) [inline plugins/saveactions.c:279]: `ft == NULL` means `doc->file_type` is NULL, but its not set before being dereferenced at **here** below

File: plugins/saveactions.c [hunk 4]
```diff
@@ -260,23 +262,36 @@ static void instantsave_document_new_cb(GObject *obj, GeanyDocument *doc, gpoint
...
+			g_warning("%s", message);
+			g_free(message);
+			return;
+		}
+
+		close(fd); /* close the returned file descriptor as we only need the filename */
+
 		doc->file_name = new_filename;
 
 		if (doc->file_type->id == GEANY_FILETYPES_NONE)
```
Comment (elextr) [inline plugins/saveactions.c:297]: **here**

File: plugins/saveactions.c [hunk 5]
```diff
@@ -260,23 +262,36 @@ static void instantsave_document_new_cb(GObject *obj, GeanyDocument *doc, gpoint
...
+		/* create new file */
+		fd = g_mkstemp(new_filename);
+		if (fd == -1)
+		{
+			gchar *message = g_strdup_printf(
+				_("Instant Save filename could not be generated (%s)."), g_strerror(errno));
+			ui_set_statusbar(TRUE, "%s", message);
+			g_warning("%s", message);
+			g_free(message);
+			return;
```
[the remark this answers is not in the document]
Comment (eht16) [reply plugins/saveactions.c:291]: Fixed, thanks for spotting.

File: plugins/saveactions.c (hunk 3 above)
Comment (eht16) [reply plugins/saveactions.c:279]: Great, you are uncovering very old bugs :). Should be fixed.

**Comment by eht16** [comment]
@elextr anything left?

**Comment by eht16** [comment]
Pinging again @elextr or anyone else.
I think it would be cool to have this in 1.38.

**Comment by elextr** [comment]
LGBI, its a plugin, so can be disabled if it goes horribly wrong, so fine by me.
