### PR TITLE
Fix the symbols tree hierarchy when several tags have the same name

### LINKED ISSUE #1583: json tree looks broken
i only have a screenshot of the problem, but i think it speaks for itself. can you help me create some printable output regarding this? just a geany user not a developer.

[url](http://i.imgur.com/YbRCJ8g.png)

geany verison: 1.29
OS: debian 9.1

[Note: edited to make your url work]

### PR DESCRIPTION
**Pull request by b4n**
Fix the symbols tree hierarchy by considering the whole scope when adding a tag, avoiding choosing the wrong parent when several tags have the same name.  Until now, to avoid such misbehavior we only used to choose the parent candidate that appeared last (line-wise) before the child.  It works in most typical situations as generally tag names are fairly unique, and children appear right after their parent.

However, there are cases that are trickier and cannot be handled that way.  In the following valid C++ snippet, it is impossible to know whether `function` should be listed under the namespace `A` or the
class `A` without looking at its full scope:

```C++
namespace A {
    namespace B {
        class A {
            void method() {}
        };
    };
    void function() {}
};
```

And it is a real-world problem for some parsers like the JSON parser that generates numeric indices for array elements name, often leading to several possibly close duplicates.

Additionally, to prevent trying to set a tag as its own parent, the code guarded against accepting a parent if the child had the same name, lading to incorrect hierarchy for `method` in cases like this:

```C++
namespace A {
    class A {
        void method() {}
    };
};
```

So to fix this, consider the whole hierarchy of a tag for choosing its parent, when that information is available from the parser.

Fixes #1583.

### CODE REVIEW

File: src/tagmanager/tm_tag.c [hunk 1]
```diff
@@ -693,6 +693,47 @@ const gchar *tm_tag_context_separator(TMParserType lang)
 	}
 }
 
+gboolean tm_tag_has_full_context(TMParserType lang)
```
Comment (kugel-) [inline src/tagmanager/tm_tag.c]: I think this is a misnomer, since it doesn't operate on a tag. I think it would fit better in tm_parser.c, as `tm_parser_has_full_context()`

File: src/symbols.c [hunk 2]
```diff
@@ -1147,21 +1126,46 @@ static void parents_table_tree_value_free(gpointer data)
...
+	const gchar *name;
+	gchar *name_free = NULL;
 	GTree *tree;
-	if (g_hash_table_lookup_extended(table, tag->name, NULL, (gpointer *) &tree) &&
-		! utils_str_equal(parent_name, tag->name) /* prevent Foo::Foo from making parent = child */)
+
+	if (EMPTY(tag->scope))
+	{
+		/* simple case, just use the tag name */
+		name = tag->name;
```
Comment (techee) [inline src/symbols.c]: What about doing g_strdup(tag->name) here and once more below and completely eliminating the name_free variable?

File: src/symbols.c [hunk 3]
```diff
@@ -1147,21 +1126,46 @@ static void parents_table_tree_value_free(gpointer data)
...
+	}
+	else if (! tm_tag_has_full_context(tag->lang))
+	{
+		/* if the parser doesn't use fully qualified scope, use the name alone but
+		 * prevent Foo::Foo from making parent = child */
+		if (utils_str_equal(tag->scope, tag->name))
+			name = NULL;
+		else
+			name = tag->name;
```
Comment (techee) [inline src/symbols.c]: g_strdup()

File: src/symbols.c [hunk 4]
```diff
@@ -1314,20 +1318,20 @@ static void update_tree_tags(GeanyDocument *doc, GList **tags)
 
 	/* Build hash tables holding tags and parents */
 	/* parent table is GHashTable<tag_name, GTree<line_num, GtkTreeIter>> */
```
Comment (techee) [inline src/symbols.c]: The comment should be updated to make it clear it's tag with context when available.

File: src/tagmanager/tm_tag.c (hunk 1 above)
Comment (techee) [reply src/tagmanager/tm_tag.c]: That's a good point. Since we now have tm_parser.c/h files where also the tag mappings are present, it seems to be a good place for this function too. And tm_tag_context_separator(), tm_tag_langs_compatible() should be moved there too so all these parser-specific mappings are at one place.

File: src/symbols.c (hunk 2 above)
Comment (b4n) [reply src/symbols.c]: That was a vain attempt at over-optimization to avoid memory allocation in the simple case.  And it'd need profiling, but it might be worth it as it's likely to be the most common case (root scope symbol and no duplicate).  But if it just adds complexity for the reader I'll drop it.

Comment (techee) [reply src/symbols.c]: Ah, OK, makes sense then. It was just a suggestion, it can stay the way it is.

File: src/tagmanager/tm_tag.c (hunk 1 above)
Comment (b4n) [reply src/tagmanager/tm_tag.c]: Yes, it makes more sense to have them in tm_parser.  I actually thought so, but placed it next to the similar functions we already had.
Now I added a commit moving them all to tm_parser.

**Comment by b4n** [comment]
@kugel- thanks for the review.
@techee no worries, and thanks for the review!  I pushed a couple of fixes, please give it a look whenever you have time :)

> it's a bit unfortunate there's yet another parser-specific mapping necessary but there's not much we can do about it.

Yeah… ideally the parser would be able to report the scope separator it uses, and they would all report fully qualified scope, but that's some work on that side.

**Comment by techee** [comment]
LGTM :-)
